### ISSUE TITLE
Columns mapping doesn't work when the component is launched inside a Dialog

### ISSUE THREAD

**Issue by alexandredoria** [FlatFilers/Adapter#35]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

If the FlatFile Component is launched inside a Dialog, the dropdown seems to be broked when I want to map the file columns...
The dropdown populate the correct options but then quickly disappear within a second, before I can choose the desired option.
    
Perhaps the problem is been related with the <b><i>CSS classes is-focused and is-open</i></b> on the dropdown.

Run on Codesandbox
[![Edit issue35](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/issue35-ow8bo?fontsize=14&hidenavigation=1&theme=dark)

**Update**
Seems the problem only occurs in Chrome browser

**Comment by dboskovic** [comment]
@alexandredoria - that codesandbox link might not have been saved

**Comment by alexandredoria** [comment]
Sorry, but now is ok.

Run on Codesandbox
[![Edit issue35](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/issue35-ow8bo?fontsize=14&hidenavigation=1&theme=dark)

**Comment by mrpbrain** [comment]
@alexandredoria Thank you for bringing this to our attention! 
Your codesandbox is helpful. I have replicated the issue, and confirmed that it still happens in v2. We'll get this resolved!

**Comment by mrpbrain** [comment]
Solution for this:

On the code for your Material UI dialog, if you add the following attributes, Flatfile should work properly:
​
```
disableAutoFocus={true}
disableEnforceFocus={true}
```

See example here, on Lines 34-35:
https://codesandbox.io/s/issue35-forked-05thh?file=/src/App.js:753-815

For technical reference, the root cause is that Material UI essentially intercepts all of Flatfile's events, by default. You can find more information about it here, if you are so inclined:
https://github.com/mui-org/material-ui/issues/13020
